'use client';
import type { Bin } from '../lib/dock-types';
export const presets = [
  { name: 'Midnight watch', brief: 'Assemble the night watch, a festival crew, and the everyday sailing crew.', bins: [{ id:'spooky',label:'Night Watch',description:'Undead, supernatural, ghostly or vampire themes.' },{ id:'bright',label:'Festival Crew',description:'Colorful, rainbow, golden or celebratory traits.' },{ id:'crew',label:'Deck Crew',description:'Ordinary human sailors and practical shipboard outfits.' }] },
  { name: 'Royal expedition', brief: 'Cast a royal delegation, a ghost crew, and a festival crew from the supplied traits.', bins: [{id:'royal',label:'Royal Delegation',description:'Crowns, regal accessories, formal naval outfits, or officer-like attire.'},{id:'ghost',label:'Ghost Crew',description:'Zombies, vampires, ghosts, and other supernatural character types.'},{id:'festival',label:'Festival Crew',description:'Rainbow characters, bright celebratory outfits, or festive accessories.'}] },
];
export default function OrdersEditor({ brief, bins, locked, onBrief, onBins, onPreset }: {brief:string;bins:Bin[];locked:boolean;onBrief:(s:string)=>void;onBins:(b:Bin[])=>void;onPreset:(i:number)=>void}) {
  return <section className="orders-editor"><div className="editor-heading"><div><p className="section-label">WRITE THE CAPTAIN’S ORDERS</p><h3>Your criteria. Jev’s decisions.</h3></div><div className="preset-buttons">{presets.map((p,i)=><button key={p.name} disabled={locked} onClick={()=>onPreset(i)}>{p.name}</button>)}</div></div>
    <label className="brief-label">Captain’s brief<textarea value={brief} onChange={e=>onBrief(e.target.value)} maxLength={1200} disabled={locked} rows={2} placeholder="Describe the crew you want to assemble…" /></label>
    <div className="criteria-grid">{bins.map((bin,i)=><fieldset key={bin.id} disabled={locked}><legend>Pile {i+1}</legend><label>Pile name<input aria-label={`Pile ${i+1} name`} value={bin.label} maxLength={40} onChange={e=>onBins(bins.map((b,j)=>j===i?{...b,label:e.target.value}:b))} /></label><label>Who belongs here?<textarea aria-label={`Pile ${i+1} criteria`} value={bin.description} maxLength={600} rows={3} onChange={e=>onBins(bins.map((b,j)=>j===i?{...b,description:e.target.value}:b))} /></label><button className="remove-pile" disabled={bins.length<=2} onClick={()=>onBins(bins.filter((_,j)=>j!==i))}>Remove pile</button></fieldset>)}</div>
    <div className="editor-bottom"><button disabled={locked || bins.length>=6} onClick={()=>onBins([...bins,{id:`pile_${Date.now().toString(36)}`,label:`Crew ${bins.length+1}`,description:''}])}>+ Add pile</button><p>{locked?'These are the submitted orders. Choose New run to edit and request new decisions.':'Define 2–6 piles, then start sorting. Names and criteria go directly to Jev. An extra review pile handles uncertainty.'}</p></div>
  </section>;
}
